### ISSUE TITLE
"self is not defined" error in React after upgrading to 3.0.0

### ISSUE THREAD

**Issue by karanmartian** [github/fetch#657] opened 2018-09-11 09:31 UTC
Hi, I just upgraded, but seeing this issue. Any suggestions?

``` 
/home/karan/Desktop/hbwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:8
[0]     searchParams: 'URLSearchParams' in self,
[0]                                        ^
[0]
[0] ReferenceError: self is not defined
[0]     at /home/karan/Desktop/hbwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
[0]     at support.searchParams (/home/karan/Desktop/hbwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
[0]     at Object.<anonymous> (/home/karan/Desktop/hbwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
[0]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[0]     at Module.load (internal/modules/cjs/loader.js:612:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[0]     at Module.require (internal/modules/cjs/loader.js:650:17)
[0]     at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by mislav** [comment] 2018-09-11 09:50
Hi could you tell us more about your module loader setup? Where does this happen, during compilation or execution in the browser? The more information the better, thank you!

**Comment by davekedar** [comment] 2018-09-11 10:10
I am using Expo for react native, after y'day all my new project breaks while loading. please help, this is due to upgrade from 2.0.4 to 3.0.0

**Comment by davekedar** [comment] 2018-09-11 10:16
What is the solution?

**Comment by karanmartian** [comment] 2018-09-12 03:49
@mislav mine is a React project and not React Native. This error happens at build time. I assume i need this polyfill for plain React projects

**Comment by davekedar** [comment] 2018-09-12 03:53
@mislav you are not getting the point, when we create the new project in Expo for react native it is fetching all the dependancies, thus this update is braking the initial loading. 

@karanmartian you can try restrict the version to 2.0.4 untill we get solution for this, it worked for me in react native

**Comment by msafari** [comment] 2018-09-12 14:44
I'm also seeing this exact error in our project which is a React project.

**Comment by msafari** [comment] 2018-09-12 15:35
ok, changing to the new `import { fetch as fetchPolyfill } from 'whatwg-fetch'`
fixed it.
The issue was odd because our own package.json dependency is still on 2.0.4. But looks like `isomorphic-fetch` which is a dependency of one of our dependencies, pulls in the 3.0.0 and somehow our app tries to use the 3.0 version for our internal code as well instead of using 2.0.4. 
Anyways, using the new import method seems to fix it.

**Comment by mislav** [comment] 2018-09-12 15:57
@msafari Thank you for sharing!

@karanmartian @davekedar How is `whatwg-fetch` declared as a dependency in your projects? What happens if you try an ordinary import like `import 'whatwg-fetch'`, and then use `window.fetch()` normally? (In React Native, it's highly likely that our polyfill isn't even needed.)

**Comment by msafari** [comment] 2018-09-12 16:18
yeah I also swapped to use the native one earlier and works fine on all browsers including IE11. The polyfill wasn't even needed for our case :D

**Comment by msafari** [comment] 2018-09-12 19:06
@mislav but that's exactly how we were using it that led to the react error mentioned in this issue with v3.0.0

**Comment by mislav** [comment] 2018-09-12 19:36
@msafari Ah, I see.

**Comment by davekedar** [comment] 2018-09-13 05:28
@mislav https://forums.expo.io/t/cant-find-variable-self/13547/9 please go through the link and you will find the problem and solution 

this is 
React Native with Expo environment

**Comment by AstRonin** [comment] 2018-09-20 08:00
I have similar error on react-native v.0.55.4 with v.3.0.0
This suggestion `import { fetch as fetchPolyfill } from 'whatwg-fetch'` did not help...

![screenshot_20180920-114804](https://user-images.githubusercontent.com/2378239/45804240-9beab280-bccc-11e8-9e81-dbc386a6ad12.jpg)

**Comment by davekedar** [comment] 2018-09-20 08:59
@AstRonin https://stackoverflow.com/questions/52269560/react-native-expo-cant-find-variable-self follow this question for the answer for the same, let me know if you can not solve it

**Comment by AstRonin** [comment] 2018-09-20 09:19
yes, on v.2.0.4 it works, but I need implementation of Fetch Abort in v.3.0.0, thats why I need new version

**Comment by monsieurnebo** [comment] 2018-10-02 07:27
Downgrading to **v2.0.4** works.

**Comment by JustFly1984** [comment] 2018-10-29 09:22
I'm confirming an issue in SSR React.js app with update to 3.0.0 from 2.0.4

**Comment by wmertens** [comment] 2018-11-20 11:54
The problem is in the umd build. You can see it here: https://unpkg.com/whatwg-fetch@3.0.0/dist/fetch.umd.js

It references `self` but doesn't define it anywhere.

**Comment by mislav** [comment] 2018-11-20 11:57
@wmertens `self` is a standard part of DOM and as such doesn't need to be defined anywhere to work. https://html.spec.whatwg.org/multipage/window-object.html#dom-self

**Comment by wmertens** [comment] 2018-11-20 12:53
in that case, webpack 4 is somehow not doing that

**Comment by wmertens** [comment] 2018-11-20 13:36
Oh I misread that - the problem is happening on the Node side, somehow Node was running whatwg-fetch on the server during SSR :-/ I'll need to investigate why that's happening, but then it's not a `whatwg-fetch` issue.

**Comment by mislav** [comment] 2018-11-21 00:04
> I'll need to investigate why that's happening, but then it's not a `whatwg-fetch` issue.

Please do investigate, I'd be grateful!

None of these reports sound like any of this is a whatwg-fetch issue. We built a polyfill for web browsers; our v3.0.0 works in every browser that we advertise supporting, as well as in service worker environment (that's why we use `self` instead of `window`). If a JavaScript execution environment doesn't implement basic DOM, maybe it shouldn't be trying to load our library meant for browsers.

**Comment by hansnull** [comment] 2018-11-29 14:51
`self` might be `undefined` in unit tests.

**Comment by wmertens** [comment] 2018-11-29 15:40
I must have been pulling in whatwg-fetch in node for a while now, and in
3.0 that started erroring? Not sure, in any case 3.0 works fine now, I
cleaned up my imports a bit.

Wout.

On Nov 29, 2018 3:51 PM, "hansnull" <notifications@github.com> wrote:

self might be undefined in unit tests.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/github/fetch/issues/657#issuecomment-442860940>, or mute
the thread

**Comment by spinualexandru** [comment] 2018-12-05 09:03
It was fixed here: https://github.com/facebook/react-native/pull/10247

**Comment by mislav** [comment] 2018-12-05 13:11
@spinualexandru That thread says that this was fixed in React Native v0.39 more than 2 years ago. I don't think that problem and the current problem are related.

**Comment by invyctus92** [comment] 2018-12-08 09:08
I use the latest version of React Native and wikijs that uses the latest version of whatwg-fetch. It doesn't work but if I enable the debug function it works correctly. I don't know if this can be useful. Here is my file package. 

`{
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "querystring": "^0.2.0",
    "react": "16.6.3",
    "react-native": "0.57.7",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "3.0.5",
    "react-navigation-tabs": "1.0.1",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "wikijs": "4.10.0",
    "xmldom": "^0.1.27",
    "xpath": "0.0.27"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}`

**Comment by TimurAsayonok** [comment] 2019-01-15 16:51
@mislav So, you would like to say, that version 3.0.0 won't work with React-Native? Have you decided to make such global changes?

**Comment by lquixada** [comment] 2019-01-16 08:04
just wanted to let you guys know that if you want the `whatwg-fetch` v3 to work on React Native or IE11, please take a look at [cross-fetch](https://github.com/lquixada/cross-fetch). It wraps `whatwg-fetch` around with a script to handle the incompatibilities.

**Comment by TimurAsayonok** [comment] 2019-01-16 13:17
@lquixada and can we use `Aborting requests`?

**Comment by lquixada** [comment] 2019-01-16 16:10
@TimurAsayonok cross-fetch is just a proxy, you're limited to what whatwg-fetch can do.

**Comment by TimurAsayonok** [comment] 2019-01-16 17:12
@lquixada Yes, I have test it on IOS and looks like working. Thank you!

**Comment by kopax** [comment] 2019-01-18 04:20
We have the same error, is it possible to fix this?

**Comment by TimurAsayonok** [comment] 2019-01-18 06:51
@kopax Try to use cross-fetch as @lquixada told.

**Comment by idMolotov** [comment] 2019-02-28 10:18
The problem is still exists.

Trying to render component within SSR:
```
....../node_modules/whatwg-fetch/dist/fetch.umd.js:8
    searchParams: 'URLSearchParams' in self,
                                       ^
ReferenceError: self is not defined
    at ....../node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at support.searchParams (....../node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
    at Object.<anonymous> (....../node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (module.js:653:30)
    at Module._compile (....../node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (....../node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Switching on the `cross-fetch@3.0.1` is not working due to the using of the same version of the `whatwg-fetch@3.0.0` inside it.


Now, the only solution is to rollback to the  "whatwg-fetch": "^2.0.4". Be ready to rework 'Headers' to the standards objects.

**Comment by rpellerin** [comment] 2019-03-05 11:30
To fix this, an easy solution would be to add a [`browser` field in `package.json`](https://docs.npmjs.com/files/package.json#browser) that points to `dist/fetch.umd.js`.
It would also help Webpack find the right file. (https://webpack.js.org/configuration/resolve/)

**Comment by conor909** [comment] 2019-05-12 14:22
Im getting this on the latest to date (`^4.3.1`) of the browser sdk

**Comment by monico-moreno** [comment] 2019-05-24 19:58
Using the temp fix suggested in the [above comment](https://github.com/github/fetch/issues/657#issuecomment-468217469) by @idMolotov 's , fixed my issue (for now). 

Quoted temp fix below for convenience:
```
Now, the only solution is to rollback to the "whatwg-fetch": "^2.0.4". Be ready to rework 'Headers' to the standards objects.
```

**Comment by jamie-ctm** [comment] 2019-08-13 07:19
I used node-fetch  currently at 2.6.0 to get around this, rather than fetch.

**Comment by callumacrae** [comment] 2019-12-09 11:00
This is also causing issues with server-side rendered Vue apps.

I'm not calling fetch on the backend—I would not expect that to work—but in 1.x and 2.x it was possible to import the library. Now it errors on import on the server which means it isn't possible to use this library in server-side rendered apps in the same way.

**Comment by kopax** [comment] 2020-02-27 11:16
Hi, I am having an issue with expo sdk36, I use whatwg-fetch 2.0.4, is it working with native app ? 

Thanks for help https://forums.expo.io/t/expo-fetch-not-working-instead-it-throw-an-error/33872

**Comment by mislav** [comment] 2020-02-27 12:49
@kopax Your error says “Network request failed”, which leads me to believe it's a network-related runtime error and not a load error with this library, which this thread is all about.

**Comment by kopax** [comment] 2020-02-27 17:34
@mislav, I know. To be honest, I am currently stuck not being able to request anything in the middle of an app development. I would have never expected this, I was hoping to find one or two fellow that have been through that error.

**Comment by jungdj** [comment] 2020-06-25 08:53
@mislav 
As far as I know, this issue is same with #253 
Hope it helps

**Comment by JakeChampion** [comment] 2020-07-08 17:40
Fix for this will be https://github.com/github/fetch/pull/794

**Closed** 2020-07-09 10:46 UTC

**Comment by karanmartian** [comment] 2020-08-06 14:19
Hey Guys, please help after upgrading to latest version of whatwg-fetch

I am seeing this error

TypeError: Cannot use 'in' operator to search for 'URLSearchParams' in false
    at /home/karan/Desktop/repos/idwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:10:37
    at /home/karan/Desktop/repos/idwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66
    at Object.<anonymous> (/home/karan/Desktop/repos/idwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/karan/Desktop/repos/idwapp/functions/index.js:1:143379)
error: Forever detected script exited with code: 1
error: Script restart attempt #9
/home/karan/Desktop/repos/idwapp/node_modules/whatwg-fetch/dist/fetch.umd.js:10
    searchParams: 'URLSearchParams' in global,
