### ISSUE TITLE
HTTP2 pseudo headers

### ISSUE THREAD

**Issue by CarmeloPatti** [github/fetch#877] opened 2020-12-08 14:59 UTC
Hallo and thanks :)

I am dealing with the following error
<img width="566" alt="image" src="https://user-images.githubusercontent.com/63046420/101499806-f89a1c80-396d-11eb-8e28-65305e95af5c.png">
according to Sentry, this happens only in Chrome 81 and after further investigation, it appears that it is caused by the presence of these pseudo headers (https://tools.ietf.org/html/rfc7540#section-8.1.2.3)
```
:method
:scheme
:authority
:path
```
![image](https://user-images.githubusercontent.com/63046420/101500132-5af31d00-396e-11eb-821b-c32f7fbbebda.png)

is this familiar to someone?

Thank you!

**Comment by JakeChampion** [comment] 2020-12-11 23:04
@CarmeloPatti  could you provide a minimal example code which reproduces the issue please?

**Comment by CarmeloPatti** [comment] 2020-12-14 16:40
sure https://gist.github.com/CarmeloPatti/3cda5c6590442542ab9540ff2363d59f

**Comment by JakeChampion** [comment] 2020-12-14 16:58
Thanks, pseudo-headers are no supported as headers which can be set. 

If you try the same request using a native fetch implementation you will see a similar error being thrown.

```js
fetch('https://google.com', {
  headers: {
    ':authority': 'www.some.com',
    ':method': 'POST',
    ':path': '/',
    ':scheme': 'http',
  },
});
```

Here is Firefox's native fetch throwing an error:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1569131/102110472-19aab380-3e2d-11eb-8df7-b74fe09688df.png">

Here is Chrome's native fetch throwing an error:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1569131/102110564-3941dc00-3e2d-11eb-839d-d7bff42c5bd3.png">


Here is Safari's native fetch throwing an error:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1569131/102110751-74440f80-3e2d-11eb-84b7-5d7fd9b1a700.png">


It looks like this is not a bug at all and is working correctly

**Comment by CarmeloPatti** [comment] 2020-12-14 17:04
I see, thanks! 

would it be an option to add `throw new TypeError('Invalid character in header field name' + name)` so that it would be easy to find the culprit header?

**Comment by JakeChampion** [comment] 2020-12-14 17:25
> I see, thanks!
> 
> would it be an option to add `throw new TypeError('Invalid character in header field name' + name)` so that it would be easy to find the culprit header?

Yes, if you want to submit that as a pull-request I would be happy to review it 👍

**Comment by CarmeloPatti** [comment] 2020-12-14 17:43
awesome :) will do, thank you for your help

**Comment by JakeChampion** [comment] 2020-12-14 20:02
I'll close this issue now as we know the answer is that pseudo headers are not supported 😄  
When you open a pull-request, I'll make sure to review it and run the test suite 👍

**Closed by JakeChampion** 2020-12-14 20:02 UTC

**Comment by CarmeloPatti** [comment] 2020-12-14 20:15
yes, the PR is already open :) side note: my original error does not come from pseudo headers manually added, but somehow chrome 81 uses the polyfill and appends those headers. anyway once the library is updated we will uncover the mystery hopefully 🤞 thank you again!
