### ISSUE TITLE
Use `XDomainRequest` in IE9?

### ISSUE THREAD

**Issue by briandipalma** [github/fetch#176] opened 2015-07-15 21:17 UTC
I was wondering if it would be possible to use the `XDomainRequest` constructor in IE9 to allow cross domain requests to work as they do in modern browsers? The API appears to be the same although ideally you'd only want to use `XDomainRequest` for IE9 and not in IE10 so maybe a browser sniff check might be required...

**Comment by matthew-andrews** [comment] 2015-07-15 22:33
I had a go at making this work a while back (branch is very out of date):-
https://github.com/github/fetch/pull/79

**Comment by noahcooper** [comment] 2015-07-15 22:36
There are a few very serious limitations of XDomainRequest that make it unusable IMO, namely:

1) It does not allow for setting the Content-Type header
2) Even though it supports cross-domain requests with CORS, it requires that requests be "same-scheme", meaning a page served over HTTP cannot make a request over HTTPS

**Comment by dgraham** [comment] 2015-07-16 06:23
Closing as a duplicate of #79.

**Closed by dgraham** 2015-07-16 06:23 UTC

**Comment by briandipalma** [comment] 2015-07-17 13:18
If `open` fails and `XDomainRequest` exists then attempt the request using it. I'm not suggesting to replace XHR in all cases. If it's only used when an `open` throws an exception then it can't be any worse then doing nothing.

**Comment by matthew-andrews** [comment] 2015-07-18 00:33
@briandipalma not sure if it's useful to you but we ended up giving up on trying to make XDomainRequest work (it just wasn't good enough for us for any but the most basic cases) and instead a [fetch-like jsonp library](https://github.com/Financial-Times/n-jsonp-fetch)……
