### ISSUE TITLE
Make use of responseType=blob conditional

### ISSUE THREAD

**Issue by vdonich** [github/fetch#490] opened 2017-03-06 18:30 UTC
At the moment, the polyfill sets `responseType='blob'` unconditionally.
However, for the purpose of using `<link rel="preload"` for non-blob responses, the above responseType shouldn't be set in some cases.

I'm not sure which way is the best, maybe adding a responseType to supports object and then exposing it for modification on fetch similarly to `polyfill = true` would make sense?

**Comment by dgraham** [comment] 2017-05-12 16:21
Related to, and possible duplicate of, #481.

**Comment by boubechtoula** [comment] 2018-10-17 15:40
t

**Comment by JakeChampion** [comment] 2020-07-09 10:51
Since https://github.com/github/fetch/pull/752 was merged, we no longer unconditionally set the responseType to blob.

I'll close this issue as I believe it is now resolved. If it is still an issue please comment and I will reopen and investigate :-)

**Closed by JakeChampion** 2020-07-09 10:51 UTC
