### ISSUE TITLE
PR #798 introduced a bug

### ISSUE THREAD

**Issue by ravirajn22** [github/fetch#849] opened 2020-10-06 10:02 UTC
```
    if (init && typeof init.headers === 'object' && !(init.headers instanceof Headers)) {
      Object.getOwnPropertyNames(init.headers).forEach(function(name) {
        xhr.setRequestHeader(name, normalizeValue(init.headers[name]))
      })
    } else {
      request.headers.forEach(function(value, name) {
        xhr.setRequestHeader(name, value)
      })
    }
```

This change which was made to fix header normalisation, should use `request.headers` in the forEach instead of `init.headers` in the first `if`. 

This caused regressions like request.headers will always have `content-type` set whereas `init.headers` might not.

**Comment by JakeChampion** [comment] 2020-10-13 11:22
Hi @ravirajn22, could you please create a small reproducible test case for this, I'd like to know that what you expect to happen does indeed happen in browsers which support the full fetch specification.

**Comment by ravirajn22** [comment] 2020-10-13 11:43
This polyfill is used internally by react-native, so don't know about how it is used in web. The only thing I saw was this change created a regression, I will see how to create a test case.

But can you explain this, why use `init.headers` inside the `if` and `request.headers` inside the `else` for iterating over headers.

**Comment by JakeChampion** [comment] 2020-10-13 13:46
Because it is the only way we have to find out if custom headers were supplied. `request.headers` always exists but `init.headers` only exists if custom headers were supplied.

**Comment by vantuan1994** [comment] 2020-10-19 21:14
is:open label:wontfix comments:>50

**Comment by vantuan1994** [comment] 2020-10-19 21:15
> ```
>     if (init && typeof init.headers === 'object' && !(init.headers instanceof Headers)) {
>       Object.getOwnPropertyNames(init.headers).forEach(function(name) {
>         xhr.setRequestHeader(name, normalizeValue(init.headers[name]))
>       })
>     } else {
>       request.headers.forEach(function(value, name) {
>         xhr.setRequestHeader(name, value)
>       })
>     }
> ```
> 
> Thay đổi này được thực hiện để sửa lỗi chuẩn hóa tiêu đề, sẽ sử dụng `request.headers`trong forEach thay vì `init.headers`trong lần đầu tiên `if`.
> 
> Điều này gây ra các hồi quy như request.headers sẽ luôn được `content-type`đặt trong khi `init.headers`có thể không.

**Closed** 2020-12-11 23:09 UTC
