### ISSUE TITLE
request failed Error: unsupported BodyInit type

### ISSUE THREAD

**Issue by hawx1993** [github/fetch#580] opened 2017-11-01 12:04 UTC
request failed Error: unsupported BodyInit type
    at Request.Body._initBody (fetch.js:231)

in my react-native project, I used fetch to encapsulate a method:

```javascript
import 'whatwg-fetch';

export const fetchApi = (params)  => {
  let { api, method, data = {}, stringify = true, ContentType } = params;
  return new Promise((resolve, reject) => {
    return fetch(api.url.href, {
      method: method || "GET",
      headers: {
        'Content-Type': ContentType || 'application/json'
      },
      body: stringify ? JSON.stringify(data) : data
    }).then((resp) => {
      if (resp.ok)  return resp.json()
     ...
    }).then((data) => {
      resolve(data)
    }).catch((error) =>{
      reject(error);
      console.log('request failed', error)
    })
  })
}
```

and I request the network :
```javascript
import { fetchApi } from '../../../../libs'

  handleRiderSearch(event){
    let { cityId } = this.props.detail;
    let text = event.nativeEvent.text;
    let params = {
      api: riderSearchApi,
      method: 'POST',
      data: {
        cityId: cityId,
        key: text
      },
      stringify: false,
      ContentType: 'application/x-www-form-urlencoded;charset=UTF-8'
    }
    fetchApi(params).then((data) => {
      console.log(data)
    }).catch((err) => {
      console.log(err)
    })
  }
```
I get every params by correctly

**Comment by caominjie** [comment] 2018-01-02 10:07
data need JSON.stringify

**Comment by DaniloCouto** [comment] 2018-04-02 12:37
Still happens.

My code : 
`let response = await fetch(url,options);`

My HTTP Options :
```
body : '{"empresaId":null,"ddi":"55","phoneNumber":"14981604811","token":null,"codigoAtivacao":null,"idOneSignal":"1539d59d-48af-4921-8274-f69d87a13905","modelo":"SM-J120H","id":null,"uuid":"a6bbf9e4f6eeef9"}',
method : "POST",
headers : {
  ApiKey : "xxxx",
  Content-Type : "application/json",
  SecretKey : "yyyy"
}
```

The error : 
`Uncaught Error: unsupported BodyInit type`

My method returns an 204, with no response, could be it the problem ? the fetch is trying to process an response body without having one ?

**Comment by mislav** [comment] 2018-04-03 14:45
@DaniloCouto We have a test that [empty 204 responses are supported](https://github.com/github/fetch/blob/cbb313bf09512efda9444e40fe9e8ac432ac1108/test/test.js#L786-L793) by the polyfill. Which browser do you encounter this on?

**Comment by fes300** [comment] 2018-04-03 17:05
I have the same problem with Chromium `Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)`

**Comment by fcaride** [comment] 2018-04-06 16:27
Same here!

**Comment by mislav** [comment] 2018-05-14 12:50
Does anyone here have any reproducible steps how to replicate the bug? Please note:

1. The code that initiates `fetch` in a browser;
2. The response that the server returns;
3. The browser version that the `Error: unsupported BodyInit type` happens on.

**Comment by fcaride** [comment] 2018-05-14 18:04
I managed to make it work removing the line:
 GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest; 

And then debugging it with the react native debugger rightclicking in anywhere and selecting enable network Monitor.

Regards! :D

**Comment by mislav** [comment] 2018-05-25 16:55
Closing this due to lack of evidence that this is a bug with our polyfill. Please provide more information if you disagree!

**Closed by mislav** 2018-05-25 16:55 UTC
