### ISSUE TITLE
fetch response body as ReadableStream

### ISSUE THREAD

**Issue by mbiegert** [github/fetch#1109] opened 2022-03-03 09:06 UTC
Hello there, from what I can gather from [mdn](https://developer.mozilla.org/en-US/docs/Web/API/fetch) the fetch specification defines the return value to resolve to a response object that has a body property that is a "ReadableStream". This means that we can get the response "bit by bit" as soon as it arrives instead of waiting for the whole request to finish.
This fetch implementation only resolves to a response after the "load" event has been fired on the XHR object, which only happens once the whole body is received.

It looks to me like this part of the specification is missing, was it intentionally left out because it's too complex or what are the reasons behind that? I'm trying to implement an EventSource listener in react-native which uses this library as a fetch polyfill.

**Comment by JakeChampion** [comment] 2022-03-18 12:15
@ritikBhandari yes you can 👍

**Comment by Damoness** [comment] 2022-07-13 08:36
It seems they will not add the property . https://github.com/github/fetch/issues/198#issuecomment-494361060

**Comment by JakeChampion** [comment] 2023-04-15 12:02
Closing as a duplicate of https://github.com/github/fetch/issues/746

**Closed by JakeChampion** 2023-04-15 12:02 UTC
