### ISSUE TITLE
No test case for protocol-relative URLs

### ISSUE THREAD

**Issue by stevenvachon** [github/fetch#352] opened 2016-06-15 16:21 UTC
There should be at least one for more coverage.

**Comment by mislav** [comment] 2016-06-15 16:21
What's a protocol-relative URL? A URL such as `//github.com/foo`?

**Comment by stevenvachon** [comment] 2016-06-15 16:21
Yes

**Comment by mislav** [comment] 2016-06-16 13:35
It would be easy to add such a test, but I doubt its usefulness. We only run tests in CI from `http:` protocol, so all they would be testing is the protocol-relative URLs are also done over `http:`. Ideally we should be running the test suite from `https:` as well to test that new requests are also done securely, but this complicates our test suite a lot, and I'm not sure it's worth it. Ultimately I believe that we should trust that XMLHttpRequest does the right thing re: handling of such URLs. I'm not aware of any problems it has in this space.

I'm closing this as too complex to achieve vs. low payoff. Thanks for the suggestion, though!

**Closed by mislav** 2016-06-16 13:35 UTC

**Comment by stevenvachon** [comment] 2016-06-16 13:39
I ran into an issue with a protocol-relative URL and looked through this library's test suite to see if such a test had existed and past. It would've saved me time had there been such a test.

**Comment by stevenvachon** [comment] 2016-06-16 13:41
Ideally, I think that you should be testing with a local http/https server like [st](https://www.npmjs.com/package/st) so that the tests perform faster, without the delay of a remote connection.

**Comment by mislav** [comment] 2016-06-16 14:18
We do test against a local server. That's not a problem. The problem is that to accurately test `//example.com/foo` URL support, we would have to make tests that:

1. Make requests to a domain other than the current one (`localhost`);
2. Run the test suite from more than one protocol (currenty only `http:`).

To solve (1), we would have to somehow tweak the DNS resolution of the machine running the test so it routes something like `example.com` back to the local test server. As an alternative, we could start another test server at another port, and use the new `//localhost:<port>` as the URL.

To solve (2), we would have to generate a self-signed SSL certificate so that we can serve the test suite over HTTPS.

Both are nontrivial and not something we would like to maintain. Instead, we trust that XMLHttpRequest supports these URLs well.

**Comment by stevenvachon** [comment] 2016-06-16 15:53
Start up a second local server and use IPs instead of DNS.

**Comment by stevenvachon** [comment] 2016-06-16 15:55
I've done such here:

https://github.com/stevenvachon/broken-link-checker/blob/master/test/6.public.HtmlChecker.js#L21
https://github.com/stevenvachon/broken-link-checker/blob/master/test/utils/server.js

**Comment by mislav** [comment] 2016-06-17 11:25
Thanks for the pointers. That's certainly a good approach for this, but still, we aren't motivated enough to invest coding and maintenance time into this. We don't anticipate problems with handling of protocol-relative URLs, because we defer handling of those to XMLHttpRequest.

**Comment by stevenvachon** [comment] 2016-06-17 14:49
Ok, thank you.
